### ISSUE TITLE
Provide some metrics when running check process

### ISSUE THREAD

**Issue by AlanVerbner** [coinbase/rosetta-cli#100]
**Is your feature request related to a problem? Please describe.**

When processing a mainnet blockchain from scratch it might be super interesting to have some progress feedback.

**Describe the solution you'd like**

- Understand the percentage it has already progrecessed (something like `block 1000 / 4000 (25%)` ) 
- See the blocks / second or transactions / second (`3 bps | 10 tps `)
- Some kind of ETA (`ETA 23m:12sec`)

`[STATS] Blocks: 979521 (Orphaned: 0) Transactions: 569393 Operations: 2014444 Reconciliations: 6341132 (Inactive: 4585972) | Block 1000 / 4000 (25%) | 3 bps - 10 tps | ETA 23m:12sec`

Even if this values might no be accurate (as @patrick-ogrady pointed out it might happen that some parts of the blockchain are heavier to process than others) it's also a good feedback for the user. Also we need to consider that sometimes, the people that will run this software knows what's the blockchain txs distribution and this values will actually might make a lot of sense.

Something like [this](https://asciinema.org/a/EZvZHrH81HOSHkx9PyqRLmmLN) will be enough, nothing fancier is required (IMO)

Ideally this values should be able to be turned on / off using cli params.

**Describe alternatives you've considered**

N/A

**Additional context**

We are processing a 4.5M blocks blockchain on a VPS so it would be ideal to undestand where are we.

**Comment by patrick-ogrady** [comment]
Support for this landed in [`v0.5.5`](https://github.com/coinbase/rosetta-cli/pull/142)!
