### ISSUE TITLE
Error installing with go get github.com/coinbase/rosetta-cli

### ISSUE THREAD

**Issue by fdmirza** [coinbase/rosetta-cli#116]
**Describe the bug**
Getting an error when installing rosetta-cli.

**To Reproduce**
install go with homebrew
run go get github.com/coinbase/rosetta-cli   
Error:
`# github.com/dgraph-io/badger/y`
`go/src/github.com/dgraph-io/badger/y/metrics.go:70:24: cannot convert "badger_v2_num_allocs" (type string) to type expvar.Int`
`go/src/github.com/dgraph-io/badger/y/calloc.go:49:15: cannot use n (type int) as type int64 in argument to NumAllocs.Add`
`go/src/github.com/dgraph-io/badger/y/calloc.go:62:17: cannot use -sz (type int) as type int64 in argument to NumAllocs.Add`

**Expected behavior**
rosetta-cli command should start working

**Additional context**

**Comment by fdmirza** [comment]
Yes, cloning the project and then `make install` worked for me. Thanks

**Comment by patrick-ogrady** [comment]
Sorry for the inconvenience! Hope to have this resolved soon!

**Comment by patrick-ogrady** [comment]
Hey @fdmirza, give this new command a try:
```
curl -sSfL https://raw.githubusercontent.com/coinbase/rosetta-cli/master/scripts/install.sh | sh -s
```
