### ISSUE TITLE
check:construction improvements

### ISSUE THREAD

**Issue by AlanVerbner** [coinbase/rosetta-cli#119]
**Is your feature request related to a problem? Please describe.**

We would like to run `check:construction` in our CI server and it would be great to have some extra features that will make it easier for us.

**Describe the solution you'd like**

1. Run `N` amount of transfers. It might be good enough to just run a couple fo transfers to check everything is fine, not to run it until the funds are drained (I mean, there is no more to pay for the fees)
2. Be able to define an address where the funds will be returned (so we don't drain test wallets. 

**Describe alternatives you've considered**

re `2` we might use `change_scenario`, will that work?

**Additional context**

We will likely run this using github actions

**Comment by patrick-ogrady** [comment]
Thanks for posting this @AlanVerbner! We've been tracking `check:construction` improvements here: https://github.com/coinbase/rosetta-cli/issues/112.

We already planned on (1), however, hadn't planned on (2). I added it to the scoped work!
