### ISSUE TITLE
Error: context canceled: unable to lookup live balance, yet summary only shows PASSED

### ISSUE THREAD

**Issue by rhyslbw** [coinbase/rosetta-cli#124]
**Describe the bug**
When [running](https://github.com/input-output-hk/cardano-rosetta/actions/runs/235202551/workflow#L59-L60) `rosetta-cli check:data` with a [configuration](https://github.com/input-output-hk/cardano-rosetta/actions/runs/235202551/workflow#L51-L52) that limits to a [small range deep into the Cardano mainnet chain](https://github.com/input-output-hk/cardano-rosetta/blob/master/test/check/configuration/src/data/shelley_sample.json), the test summary reports success, however, an error is first thrown:

```
Error: context canceled: unable to lookup live balance
+--------------------+--------------------------------+--------+
|  CHECK:DATA TESTS  |          DESCRIPTION           | STATUS |
+--------------------+--------------------------------+--------+
| Request/Response   | Rosetta implementation         | PASSED |
|                    | serviced all requests          |        |
+--------------------+--------------------------------+--------+
| Response Assertion | All responses are correctly    | PASSED |
|                    | formatted                      |        |
+--------------------+--------------------------------+--------+
| Block Syncing      | Blocks are connected into a    | PASSED |
|                    | single canonical chain         |        |
+--------------------+--------------------------------+--------+
| Balance Tracking   | Account balances did not go    | PASSED |
|                    | negative                       |        |
+--------------------+--------------------------------+--------+
| Reconciliation     | No balance discrepencies were  | PASSED |
|                    | found between computed and     |        |
|                    | live balances                  |        |
+--------------------+--------------------------------+--------+
```

**To Reproduce**
https://github.com/input-output-hk/cardano-rosetta/actions/runs/235202551/workflow

**Expected behavior**
Either not to experience the error, or to see an item in the summary with a status of `FAILED` 

**Additional context**

**Comment by patrick-ogrady** [comment]
👋  @rhyslbw what version are you on? I merged what I thought was a fix into the `v0.5.0` release in this PR: https://github.com/coinbase/rosetta-cli/pull/122/files#diff-8383d6fab9a1b498a9b5ba602e348bd6R475

**Comment by rhyslbw** [comment]
Testing with **v0.5.0 4b2226853f91b4dc5ba7a18c2e3db730165b5232** now, will provide an update once complete

**Comment by rhyslbw** [comment]
Resolved, thank you.
