### ISSUE TITLE
`check:data` requires some configuration from the `construction` object to be present

### ISSUE THREAD

**Issue by rhyslbw** [coinbase/rosetta-cli#127]
**Describe the bug**
`check:data` requires some configuration from the `construction` object to be present.

**To Reproduce**
1. Run `check:data` with a known working config file. 
2. Remove:
``` json
{
  "construction": {
    "end_conditions": {
      "create_account": 0
    },
    "workflows": [
      {
        "name": "create_account",
        "concurrency": 1
      },
      {
        "name": "request_funds",
        "concurrency": 1
      }
    ]
  }
}
```
3. Run `check:data`
**Expected behavior**
`check:data` should run without any `construction` configuration.

**Additional context**
`v0.5.0` `4b2226853f91b4dc5ba7a18c2e3db730165b5232`

**Comment by patrick-ogrady** [comment]
@rhyslbw what error do you get when you do this? I couldn't replicate your issue when testing against our `rosetta-bitcoin` instance.

I used this config file when running `check:data`:
```json
{
 "network": {
  "blockchain": "Bitcoin",
  "network": "Testnet3"
 },
 "data_directory": "bitcoin-data",
 "http_timeout": 300,
 "tip_delay": 1800,
 "disable_memory_limit": true,
 "log_configuration": false,
 "data": {
  "historical_balance_disabled": true,
  "end_conditions": {
   "reconciliation_coverage": 0.95
  }
 }
}
```

**Comment by rhyslbw** [comment]
@patrick-ogrady 
``` json
{
  "network": {
    "blockchain": "cardano",
    "network": "mainnet"
  },
  "http_timeout": 100000,
  "tip_delay": 10000,
  "sync_concurrency": 16,
  "transaction_concurrency": 32,
  "online_url": "http://localhost:8080",
  "construction": {
    "offline_url": "http://localhost:8080"
  },
  "data": {
    "start_index": 1,
    "end_conditions": {
      "index": 10000
    }
  }
}
```

``` console
2020/09/09 20:52:05 missing create_account workflow: invalid construction configuration: invalid configuration: unable to load configuration
```

**Comment by patrick-ogrady** [comment]
Ahhh this is my bad for not calling this out more clearly in the `v0.5.0` release notes, @rhyslbw. We removed the `construction` defaults (which were just Ethereum transfers). If you partially populate `construction` (as you are doing here), it will error instead of trying to populate a default script (which tends to vary by network).

You can fix this if you use the following config when testing `check:data` (just remove the `construction` field):
```json
{
  "network": {
    "blockchain": "cardano",
    "network": "mainnet"
  },
  "http_timeout": 100000,
  "tip_delay": 10000,
  "sync_concurrency": 16,
  "transaction_concurrency": 32,
  "online_url": "http://localhost:8080",
  "data": {
    "start_index": 1,
    "end_conditions": {
      "index": 10000
    }
  }
}
```

**Comment by rhyslbw** [comment]
This is my mistake really. I didn't properly observe that `offline_url` is a property of `construction`, unlike `online_url` being at the top level.
