### ISSUE TITLE
[Construction API Testing]: Does not detect balance

### ISSUE THREAD

**Issue by SmartArray** [coinbase/rosetta-cli#132]
**Describe the bug**
We are getting closer to a beta release of our node written using the JS SDK. However, we are running into some issues when testing the Construction API.

First, the Rosetta CLI instance is trying to find the balance on a random address, which is expected behaviour.
```
rosetta_cli_1       | 2020/09/13 05:04:04 processing workflow "transfer"
rosetta_cli_1       | 2020/09/13 05:04:04 looking for balance {"value":"250000000","currency":{"symbol":"DGB","decimals":8}}
rosetta_cli_1       | 2020/09/13 05:04:04 processing workflow "create_account"
rosetta_cli_1       | 2020/09/13 05:04:05 processed workflow "create_account" for job "0"
rosetta_cli_1       | 2020/09/13 05:04:05 processing workflow "transfer"
rosetta_cli_1       | 2020/09/13 05:04:05 looking for balance {"value":"250000000","currency":{"symbol":"DGB","decimals":8}}
rosetta_cli_1       | 2020/09/13 05:04:05 processing workflow "request_funds"
rosetta_cli_1       | 2020/09/13 05:04:05 looking for balance {"value":"0","currency":{"symbol":"DGB","decimals":8}}
rosetta_cli_1       | 2020/09/13 05:04:05 processed workflow "request_funds" for job "1"
rosetta_cli_1       | 2020/09/13 05:04:05 processing workflow "request_funds" for job "1"
rosetta_cli_1       | 2020/09/13 05:04:05 looking for balance {"value":"80000","currency":{"symbol":"DGB","decimals":8}} on address sn6VmygQpFCQNaWabpwmNQcixL63qAykro
rosetta_cli_1       | 2020/09/13 05:04:05 processing workflow "transfer"
rosetta_cli_1       | 2020/09/13 05:04:05 looking for balance {"value":"250000000","currency":{"symbol":"DGB","decimals":8}}
rosetta_cli_1       | 2020/09/13 05:04:05 waiting for available jobs...
rosetta_cli_1       | [STATS] Transactions Confirmed: 0 (Created: 0, In Progress: 0, Stale: 0, Failed: 0) Addresses Created: 1
```

However, as soon as I have issued a transaction of 784119600500 units, it still tries to find the balance although the following output looks very good.

```
{
    "block_identifier": {
        "index": 104,
        "hash": "d41046d0727d50c094e7e3259317f7cde6c6ac471111c5c7bb8ed11fff7b0260"
    },
    "balances": [
        {
            "value": "784119600500",
            "currency": {
                "symbol": "DGB",
                "decimals": 8
            }
        }
    ]
}
```

**To Reproduce**
- Using the official example of automated construction API testing with an Ethereum implementation.

**Expected behavior**
A transaction should be crafted and sent to the mempool.

**Question**
Is the rosetta-cli searching for the _exact_ balance on that specific account or would it be happy with a minimum balance?
I do not want you to reproduce the issue unless the latter is true. In that case I would be happy to provide further instructions to reproduce the scenario.

**Comment by patrick-ogrady** [comment]
👋 @SmartArray would you mind moving this conversation to [the community](https://community.rosetta-api.org/)? We've found its much better for helping teams walkthrough issues like this!
