### ISSUE TITLE
Add AbsoluteReconciliationCoverage to check:data end conditions

### ISSUE THREAD

**Issue by matheusd** [coinbase/rosetta-cli#147]
While running on small chains a Decred simnet (local-only network used for development with a one-second target block time), `check:data` will sometimes hang indefinitely due to not consistently reaching an end condition.

Using just `end_conditions.tip = true` will sometimes either fail (due to very fast block times) or exit too early without having checked all accounts yet.

Using `end_conditions.reconciliation_coverage = x` will sometimes also cause the check not to terminate due to very fast processing of `check:data` on simnet (it will reconcile a large % of the total accounts before reaching tip).

I'd like to add a `AbsoluteReconciliationCoverage` end condition such that we can specify an absolute % of accounts that should have been reconciled before returning (as opposed to a relative % after it has reached tip).

**Comment by patrick-ogrady** [comment]
This is a great idea @matheusd ... we will get this into the next release!
