### ISSUE TITLE
./rosetta-cli configuration:create creates empty construction data

### ISSUE THREAD

**Issue by AlexBHarley** [coinbase/rosetta-cli#181]
**Describe the bug**

The `construction` property of the configuration file is `null`. I expect it to be populated with parameters just like `data`.

**To Reproduce**

```
go run main.go configuration:validate ./config.json
```

**Expected behavior**

The `construction` property is not `null`, but has all the default properties like `StaleDepth` and `BroadcastLimit`.

**Comment by patrick-ogrady** [comment]
👋  @AlexBHarley 

We removed construction testing defaults when introducing the revamped `check:construction` testing in `v0.5.0`. Previously, we defaulted everything to the Ethereum settings but this ended up really confusing a few people who tried to run this test on their implementation (in the same way that you just run `check:data`). As I mention in the README, the best way to get started here is to look at our [Bitcoin](https://github.com/coinbase/rosetta-bitcoin/blob/master/rosetta-cli-conf/testnet/config.json)([DSL File](https://github.com/coinbase/rosetta-bitcoin/blob/master/rosetta-cli-conf/testnet/bitcoin.ros)) or [Ethereum](https://github.com/coinbase/rosetta-ethereum/blob/master/rosetta-cli-conf/testnet/config.json)([DSL File](https://github.com/coinbase/rosetta-ethereum/blob/master/rosetta-cli-conf/testnet/ethereum.ros)) examples!

**Comment by AlexBHarley** [comment]
Gotcha, thanks!
