### ISSUE TITLE
retry does not work

### ISSUE THREAD

**Issue by fdymylja** [coinbase/rosetta-cli#190]
**Describe the bug**
While testing rosetta-cli inside docker-compose, despite settings max retries to 20 and wait inbetween them to 10s it fails immediately due to connection refused.
**To Reproduce**
highlighted above
**Expected behavior**
rosetta-cli shoul be retrying
**Additional context**
version: v0.6.0

**Comment by patrick-ogrady** [comment]
👋  @fdymylja 

`rosetta-cli` only retries when the `*types.Error` returned is [`retriable` (set by the Rosetta implementation)](https://www.rosetta-api.org/docs/models/Error.html) or if the error observed is [considered transient](https://github.com/coinbase/rosetta-sdk-go/blob/1e2b4a3d02e14ed747e02fefc9cfabb9e36c3418/fetcher/utils.go#L61-L74). `Connection Refused` is not considered a transient error and is usually indicative of misconfiguration. My guess is that the port of the implementation you are testing may not be accessible by `rosetta-cli`. Make sure you include the port your implementation is running on in the URLs specified in the config (they default to `http://localhost:8080`).

For some additional context, we use this retry logic extensively throughout Coinbase and haven't had any issues with it.
