### ISSUE TITLE
Support for signature type: schnorr_1

### ISSUE THREAD

**Issue by renlulu** [coinbase/rosetta-cli#191]
**Is your feature request related to a problem? Please describe.**

Hey, when I try to use `rosetta-cli` to verify `zilliqa-rosetta`'s implementation, I get an error says:

```
Command Failed: unable to to sign payload for 0: sign: unexpected Signature type while signing: <nil>: unable to sign payloads: unable to create transaction
```

so I try to debug from cli side and notice it hasn't support `schnorr_1` signature algorithm which is needed by us zilliqa:

https://github.com/coinbase/rosetta-sdk-go/blob/master/keys/signer_secp256k1.go#L61, 

and we also notice that the spec says it already supported it:

https://github.com/coinbase/rosetta-specifications#supported-signaturetypes

so far I am a bit confused about it, so please point out the right direction for me, or let me know you do have not support it and we will wait for your work! Thanks a lot!

**Describe the solution you'd like**

Support signature type `schnorr_1`.

**Comment by renlulu** [comment]
Let me know if you are willing to let me do a PR for this : D

**Comment by patrick-ogrady** [comment]
> so I try to debug from cli side and notice it hasn't support schnorr_1 signature algorithm which is needed by us zilliqa:
https://github.com/coinbase/rosetta-sdk-go/blob/master/keys/signer_secp256k1.go#L61,
and we also notice that the spec says it already supported it:
https://github.com/coinbase/rosetta-specifications#supported-signaturetypes

You are correct, @renlulu. `rosetta-sdk-go/keys` (which powers `rosetta-cli`) does not yet have an implementation for `schnorr_1` even though the spec supports it (https://github.com/coinbase/rosetta-specifications/pull/38). This is also true for `schnorr_poseidon` and the `tweedle` curve.

The idea behind the spec leading `rosetta-sdk-go` development is that integrators don't need to use `rosetta-sdk-go` to integrate and may choose to write an implementation for their SDK of choice before we add support in the SDK (we don't want to be a blocker for anyone).

> Let me know if you are willing to let me do a PR for this : D

Go for it! I'm pretty swamped with some optimization PRs that will take the next weekish.

**Comment by renlulu** [comment]
Thanks @patrick-ogrady for your kindly reply. And Yes! We do have an implementation in our golang sdk for schnorr signature algorithm, and I think it's good to integrate it to `rosetta-cli` and will do a PR for this shortly. Thanks again!

**Comment by renlulu** [comment]
Hey, I just create a PR for this: https://github.com/coinbase/rosetta-sdk-go/pull/257, feel free to reach out me if there is anything wrong! Thanks!

**Comment by renlulu** [comment]
Hey, thanks for merging my PR. Do you have any estimated time to make `rosetta-cli` support latest `rosetta-sdk-go` : D. I tried to solve some issues locally when I upgraded the version of its dependencies but still a lot of issues I cannot clear. Seems not very trivial for me.

**Comment by renlulu** [comment]
But I will still have a try later tomorrow.

**Comment by patrick-ogrady** [comment]
We are hoping to get an update out today! 🤞 We've been working on some huge performance optimizations that should be immediately noticeable.
