### ISSUE TITLE
Boolean config options consistency

### ISSUE THREAD

**Issue by sosedoff** [coinbase/rosetta-cli#194]
Does it make sense to always favor `*_enabled` option names for boolean variables?
Having both `_enabled` and `_disabled` is a bit confusing IMO.

Was the original purpose to set the values correctly without having to specify the options in the config file?

**Comment by patrick-ogrady** [comment]
> Was the original purpose to set the values correctly without having to specify the options in the config file?

That is exactly right LOL. I have a config overhaul planned for this sprint, so hopefully will become much easier!

The other thing to note is that there is no way to set a `0` value for some options because `0` is interpreted as desiring `default`. 🤦
