### ISSUE TITLE
`rosetta-cli check` always exits with status code 1 when using `--end`

### ISSUE THREAD

**Issue by abukosek** [coinbase/rosetta-cli#20]
**Describe the bug**
When using the `--end` option to `rosetta-cli check`, it always exits with status code 1, even when there are no errors in the output.
This makes it difficult to use as part of an automated continuous-integration workflow or testing suite.

**To Reproduce**
1. Run `rosetta-cli check --end 42; echo $?`.

**Expected behavior**
If there are no validation errors, an exit code of 0 should be returned.  Exit code 1 should be returned only if validation errors have occurred.

**Comment by patrick-ogrady** [comment]
Thanks for posting this issue. I think this is a great idea.
