### ISSUE TITLE
Be able to access state from a different workflow

### ISSUE THREAD

**Issue by AlanVerbner** [coinbase/rosetta-cli#205]
**Is your feature request related to a problem? Please describe.**

When we are dealing with staking we need to create two different keys:
- Both are used to create an address that can receive funds and transfer value
- One of the keys is used to create the address where rewards are specified

If we execute the `create_account` workflow we don't think there is a way for us to look for the payment address when executing `find_account` on a different workflow, it might return the stake address which is not the one we need.

**Describe the solution you'd like**

Be able to properly filter by address when executing `find_account` 

**Describe alternatives you've considered**

Either to be able to pick an account based on a regex expression (we can filter account identifiers by bech32 prefix) or be able to save variables and tag them such that they can be used in different workflows.

**Additional context**

n/a

**Comment by patrick-ogrady** [comment]
👋 @AlanVerbner...thanks for posting this! I think providing access to a transactional KV store would empower a lot of DSL writers and I'm going to follow that route. I'll attach this issue to any relevant PRs.
