### ISSUE TITLE
Question: possible to set a start height for check:data ?

### ISSUE THREAD

**Issue by noandrea** [coinbase/rosetta-cli#231]
In the configuration is it possible to set end conditions when to stop the checks,
can I specify at which height to start syncing from a certain height?

**Comment by shrimalmadhur** [comment]
@noandrea You can specify `start_index` in the config to start syncing from the height. but I don't think so you can set the end condition. But I will try to find it there's anything for that.

**Comment by shrimalmadhur** [comment]
Actually there is end condition support - https://github.com/coinbase/rosetta-cli/blob/master/configuration/types.go#L201 
check this out. You can use this to specify the end conditions.

**Comment by noandrea** [comment]
> @noandrea You can specify `start_index` in the config to start syncing from the height. but I don't think so you can set the end condition. But I will try to find it there's anything for that.

that's what I was looking for, thanks!
