### ISSUE TITLE
Add support for Apple silicon 

### ISSUE THREAD

**Issue by maebeam** [coinbase/rosetta-cli#234]
When running `install.sh` on an M1 Mac I receive the following error:

```
coinbase/rosetta-cli crit platform darwin/arm64 is not supported.  Make sure this script is up-to-date and file request at https://github.com/coinbase/rosetta-cli/issues/new
```

**Comment by shrimalmadhur** [comment]
Hi @maebeam , sorry for the very delayed support
The new [release](https://github.com/coinbase/rosetta-cli/releases/tag/v0.7.0) has `darwin/arm64` support. Please try it and let me know if there are any issues. I will be soon updating the scripts to make sure we build those from now on.

**Comment by maebeam** [comment]
The latest release works well for me! Thank you @shrimalmadhur.

**Comment by maebeam** [comment]
Thanks again! I was struggling with xgo :)

**Comment by maebeam** [comment]
FYI:

```curl -sSfL https://raw.githubusercontent.com/coinbase/rosetta-cli/master/scripts/install.sh | sh -s

coinbase/rosetta-cli crit platform darwin/arm64 is not supported.  Make sure this script is up-to-date and file request at https://github.com/coinbase/rosetta-cli/issues/new```

**Comment by shrimalmadhur** [comment]
@maebeam It should work now with #255
