### ISSUE TITLE
Wrong progress output on Data API sync

### ISSUE THREAD

**Issue by awfm9** [coinbase/rosetta-cli#235]
The synchronization log output of the Data API uses current height divided by final height to determine the synchronization status progress. This is not correct for blockchains which don't start at a zero height.

You can reproduce this for a spork of the Flow blockchain by running the Rosetta CLI according to the instructions found here:

https://github.com/optakt/flow-dps/tree/master/cmd/flow-rosetta-server

I would expect that the Rosetta CLI would keep track of how many blocks it actually has to synchronize, rather than just using the height.

**Comment by shrimalmadhur** [comment]
merged a fix with the above PR. that should fix this.
