### ISSUE TITLE
install.sh fails to download the rosetta-cli binary for macos

### ISSUE THREAD

**Issue by xin-hedera** [coinbase/rosetta-cli#242]
**Describe the bug**
The latest release v0.7.0 added macos version 10.12 to the name of the release tgz artifact, thus the `install.sh` script fails to download it as it expects to download the file `https://github.com/coinbase/rosetta-cli/releases/download/v0.7.0/rosetta-cli-0.7.0-darwin-amd64.tar.gz`

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by shrimalmadhur** [comment]
Hi @xin-hedera - thanks for bringing this up. I have updated the current release with the correct name. Also https://github.com/coinbase/rosetta-cli/pull/241 will fix this issue further.
