### ISSUE TITLE
Txn is too big to fit into one request: unable to bootstrap balances

### ISSUE THREAD

**Issue by rufsam** [coinbase/rosetta-cli#245]
**Describe the bug**

When trying to bootstrap a large `bootstrap_balances.json` file that contains more than 35k accounts, rosetta-cli breaks with following error: **"Txn is too big to fit into one request: unable to bootstrap balances"**.

**To Reproduce**
1) create a large `bootstrap_balances.json` file that contains for example more than 35k accounts
2) link the `bootstrap_balances.json` file with the rosetta-cli configuration file
3) run the rosetta-cli data check

**Expected behavior**
I expect rosetta-cli to be able to handle large `bootstrap_balances.json` files that contain many accounts.

**Comment by shrimalmadhur** [comment]
Thanks @rufsam for bringing this up. I will take a look at it and get back to you.

**Comment by shrimalmadhur** [comment]
@rufsam great to hear it worked. And yes it makes sense to solve this issue in generic way rather than increasing system's RAM. I will create a separate issue for exploring other options.

**Comment by rufsam** [comment]
Hey @shrimalmadhur, I would like to give you a status update from my side:
The high RAM consumption due to `"memory_limit_disabled" = true` is now really a problem because rosetta-cli breaks down over time. It would be really great if this could be solved in a different way. Thanks alot for your time.
