### ISSUE TITLE
Rosetta Constructor DSL: error parsing a string containing a "-" character

### ISSUE THREAD

**Issue by rufsam** [coinbase/rosetta-cli#248]
**Describe the bug**

Hi! When using the Rosetta Constructor DSL for example following way:

```
create_account(1){
  create{
    network = {"network":"chrysalis-devnet", "blockchain":"iota"};
    key = generate_key({"curve_type": "edwards25519"});
    account = derive({
      "network_identifier": {{network}},
      "public_key": {{key.public_key}}
    });

   ...
   
  }
}
```

the Rosetta Construction API check fails. The `-` between `"chrysalis-devnet"` looks like a subtraction for the parser.

Is there a way around this issue? Can I encode the  `-` somehow?

**To Reproduce**

1) setup a *.ros file for the Construction API check
2) choose a network name that contains a `-`
3) start the Construction API check

**Expected behavior**

I expect that the network name is allowed to contain a `-` char.

Many thanks for the help.

**Comment by shrimalmadhur** [comment]
Thanks for raising this. I will take a look at it.

**Comment by shrimalmadhur** [comment]
Hello @rufsam, I took a look at the parsing logic and this indeed is a missed case in a parser. I will work on this to fix it. Meanwhile you could explicitly set the variable using something like this
```
network = set_variable({"network":"chrysalis-devnet", "blockchain":"iota"});
```

This should hopefully unblock you.

**Comment by rufsam** [comment]
Hello @shrimalmadhur, thanks again for the help. I finally could test the fix, it did work! :) Regards!

**Comment by t-hale** [comment]
@shrimalmadhur is this still an outstanding issue?  was looking to tackle something easy...

**Comment by shrimalmadhur** [comment]
> @shrimalmadhur is this still an outstanding issue? was looking to tackle something easy...

yea I haven't gotten a change to fix it. I see you have raised a PR. I will take a look. Thanks
