### ISSUE TITLE
version of latest release is incorrect

### ISSUE THREAD

**Issue by ramilexe** [coinbase/rosetta-cli#258]
**Describe the bug**
The version of the latest release is incorrect

**To Reproduce**

* Download latest release rosetta-cli-0.7.2-linux-amd64.tar.gz
* Extract it
* Run `./rosetta-cli-0.7.2-linux-amd64 version`
  and you will get 
  ```
  v0.6.7 
  ```

**Expected behavior**
You should get `of 0.7.2`

**Additional context**

**Comment by shrimalmadhur** [comment]
Hi @ramilexe 

Thanks for raising this issue. #254 resolves this. So this should be fixed in next release.

**Comment by shrimalmadhur** [comment]
This should be fixed with the new [release](https://github.com/coinbase/rosetta-cli/releases/tag/v0.7.3)
