### ISSUE TITLE
Documentation for configuration

### ISSUE THREAD

**Issue by GeekArthur** [coinbase/rosetta-cli#263]
**Is your feature request related to a problem? Please describe.**
Currently we only have [configuration examples](https://github.com/coinbase/rosetta-cli/tree/master/examples/configuration), but we don't have the definition and usage documentation of the fields in the configuration file, it's hard for a new user and asset issuer to use the configuration file properly.

**Describe the solution you'd like**
We can add the documentation including the definition of all the fields in the configuration file, also it would be better to have a documentation for `How to write a configuration file` including all the steps for onboarding.

**Comment by shrimalmadhur** [comment]
Hi @GeekArthur , thanks for raising the issue. We are actually working on something similar to provide on rosetta website. We will also link it somewhere in rosetta-cli repo. But I will update you once it is out.

**Comment by shrimalmadhur** [comment]
@GeekArthur we have updated some of our documentation. Check out the blog [post](https://community.rosetta-api.org/t/new-documents-published-to-rosetta-api-docs-v1-4-10/655)
If you think we need more improvement in some areas, feel free to suggest. I am closing this for now.
