### ISSUE TITLE
Log system issue

### ISSUE THREAD

**Issue by GeekArthur** [coinbase/rosetta-cli#272]
**Describe the bug**
Seems like we hardcode the error message instead of using the return err -> Return error message is `Account.Address is missing`, but the actual error message is `Account.SubAccount.Address is missing`
<img width="1822" alt="Screen Shot 2022-01-25 at 12 25 08 PM" src="https://user-images.githubusercontent.com/15131537/151055197-a096d29e-7772-4b99-a8d8-afdc1c9dba2f.png">

If this is a generic issue, we need to address all of them.

**To Reproduce**
Run rosetta-cli and modify the config.json to ensure it hit the line as the screenshot shows

**Expected behavior**
We need to wrap the `err` in the error message then return

**Comment by shrimalmadhur** [comment]
Thanks @GeekArthur for raising the issue. We could definitely wrap the internal error and keep the hardcoded one too so that we have a generic message plus the actual error. Feel free to contribute and wrap the internal error.

**Comment by GeekArthur** [comment]
It's fixed in new error handling mechanism
