### ISSUE TITLE
Request acocunt/coins always failed when using account-based rosetta implementation

### ISSUE THREAD

**Issue by aeharvlee** [coinbase/rosetta-cli#294]
**Describe the bug**
[One of the recent patches](https://github.com/coinbase/rosetta-cli/commit/dacb2494fde841def213ac08ae538a1171e0e00b) causes problem.
It always call `account/coins` when we run `check:construction`, but rosetta-ethereum(account-based blockchain) does not support that.

**To Reproduce**
Just run `check:construction` using `rosetta-ethereum`.

**Expected behavior**
When using account-based blockchain, `account/coins` must not be called.

**Comment by shrimalmadhur** [comment]
#297 fixed it.
