### ISSUE TITLE
curl -sSfL https://raw.githubusercontent.com/coinbase/rosetta-cli/master/scripts/install.sh | sh -s is not installing anything

### ISSUE THREAD

**Issue by WaleedRizk** [coinbase/rosetta-cli#313]
**Describe the bug**
On Windows 10, in cmd window, typing:

curl -sSfL https://raw.githubusercontent.com/coinbase/rosetta-cli/master/scripts/install.sh | sh -s

....doesn't install.

**To Reproduce**
On Win10, open CMD and run:
curl -sSfL https://raw.githubusercontent.com/coinbase/rosetta-cli/master/scripts/install.sh | sh -s

**Expected behavior**
Installs rosetta-cli

**Additional context**
coinbase/rosetta-cli info checking GitHub for latest tag
coinbase/rosetta-cli info found version: 0.7.6 for v0.7.6/windows/amd64

...but nothing installed

**Comment by king0fheart** [comment]
Same thing happening with me :(. It is not showing any installation or /bin folder.

![Untitled](https://user-images.githubusercontent.com/92843732/169531230-b539cc4d-8d7e-4538-8fe5-7a156b0bfa36.png)

**Comment by mrmr1993** [comment]
I just opened #319 for this same issue. To quote here:
> The latest release only included source code, with no build artifacts. This has broken `install.sh`.

**Comment by shrimalmadhur** [comment]
@irisZhangCB please update this issue once you upload the new binaries! Thanks

**Comment by irisZhangCB** [comment]
Uploaded binaries

**Comment by shrimalmadhur** [comment]
Closing this as related issue has been closed and binaries have been uploaded.
