### ISSUE TITLE
Starter configuration file cannot be created as instructed

### ISSUE THREAD

**Issue by WaleedRizk** [coinbase/rosetta-cli#315]
**Describe the bug**
The help indicates that a start config file can be created by rosetta-cli configuration:create.

**To Reproduce**
$ ./rosetta-cli-0.7.7-windows-amd64 configuration:create
Error: accepts 1 arg(s), received 0
Usage:
  rosetta-cli configuration:create [flags]

Flags:
  -h, --help   help for configuration:create

Global Flags:
      --block-profile string        Save the pprof block profile in the specified file
      --configuration-file string   Configuration file that provides connection and test settings.
                                    If you would like to generate a starter configuration file (populated
                                    with the defaults), run rosetta-cli configuration:create.

                                    Any fields not populated in the configuration file will be populated with
                                    default values.
      --cpu-profile string          Save the pprof cpu profile in the specified file
      --mem-profile string          Save the pprof mem profile in the specified file

Command Failed: accepts 1 arg(s), received 0

walee@DESKTOP-E2FLCS7 MINGW64 /c/workspace-minima/git/rosetta/rosetta-cli (feature/rosetta-minima-integration)
$ ./rosetta-cli-0.7.7-windows-amd64 configuration:create

**Expected behavior**
generate a starter configuration file (populated   with the defaults)

**Additional context**

**Comment by irisZhangCB** [comment]
hello @WaleedRizk a file name should be passed in as well. The command will be like:
`./rosetta-cli-0.7.7-windows-amd64 configuration:create config.json`

**Comment by shrimalmadhur** [comment]
Closing this as the above answer should work!
