### ISSUE TITLE
unable to initialize asserter???

### ISSUE THREAD

**Issue by Li-LaoShi** [coinbase/rosetta-cli#348]
Command Failed: no networks available: unable to initialize asserter
when I create project,wirte in : rosetta-cli check:data --configuration-file config/xxx.json  ,to be give me a this  error?  but my network is ok. My API can be response and request.

**Comment by GeekArthur** [comment]
The error is from this line: https://github.com/coinbase/rosetta-sdk-go/blob/f1f9fd45cdbde1589523b520be402b227bc4f9fb/fetcher/fetcher.go#L168, which means `/network/list` API doesn't return blockchain networks

Please double check two things then give a try:
* The `online_url` field is specified in `config.json` (config/xxx.json), which points to the node, docs of `config.json` is here: https://www.rosetta-api.org/docs/rosetta_configuration_file.html
* `/network/list` can return available network(s), docs of `/network/list` is here: https://www.rosetta-api.org/docs/NetworkApi.html#networklist

**Comment by Li-LaoShi** [comment]
这两件事情都是通过的，我通过 debug 让rosetta request 进入到 /network/list API中，返回值也是正确定。rosetta给我返回    Response Assertion | All responses are correctly    | PASSED     |
|                    | formatted                      |

**Comment by Li-LaoShi** [comment]
Request/Response  is FAILED .but Response Assertion is PASSED.I don`t know why

**Comment by Li-LaoShi** [comment]
if I write in : rosetta-cli check:spec --configuration-file config/xxx.json  ,it response me with : no networks available: unable to initialize asserter for online node fetcher: unable to create checkSpec object with online URL

**Comment by Li-LaoShi** [comment]
> 错误来自这一行：[https](https://github.com/coinbase/rosetta-sdk-go/blob/f1f9fd45cdbde1589523b520be402b227bc4f9fb/fetcher/fetcher.go#L168) ://github.com/coinbase/rosetta-sdk-go/blob/f1f9fd45cdbde1589523b520be402b227bc4f9fb/fetcher/fetcher.go#L168 ，这意味着`/network/list`API不返回区块链网络
> 
> 请仔细检查两件事，然后试一试：
> 
> * 该`online_url`字段在`config.json`（config/xxx.json）中指定，指向节点，文档在`config.json`这里：[https ://www.rosetta-api.org/docs/rosetta_configuration_file.html](https://www.rosetta-api.org/docs/rosetta_configuration_file.html)
> * `/network/list`可以返回可用的网络，文档在`/network/list`这里：[https ://www.rosetta-api.org/docs/NetworkApi.html#networklist](https://www.rosetta-api.org/docs/NetworkApi.html#networklist)

这两件事情都是通过的，我通过 debug 让rosetta request 进入到 /network/list API中，返回值也是正确定。rosetta给我返回Response Assertion 是 PASSED，但是 Request/Response 是 FAILED。然后键入 rosetta-cli check:spec --configuration-file config/xxx.json后，返回给我 ： no networks available: unable to initialize asserter for online node fetcher: unable to create checkSpec object with online URL。我不太明白哪个环节出现了问题
