### ISSUE TITLE
a question: :  neither PartialBlockIdentifier.Hash nor PartialBlockIdentifier.Index is set: unable to fetch tip block???

### ISSUE THREAD

**Issue by Li-LaoShi** [coinbase/rosetta-cli#352]
neither PartialBlockIdentifier.Hash nor PartialBlockIdentifier.Index is set: unable to fetch tip block
but my /block request and response is ok.  get request data from /network/status  to  /block . /network/** is validated.help help me?

**Comment by GeekArthur** [comment]
Thanks for bringing this up, you can ignore the error for now, that's an issue in check:spec

Regarding block identifier validation, you can refer to https://www.rosetta-api.org/docs/models/PartialBlockIdentifier.html and ensure the following is complied:
```
When fetching data by BlockIdentifier, it may be possible to only specify the index or hash. If neither property is specified, it is assumed that the client is making a request at the current block.
```

**Comment by Li-LaoShi** [comment]
yes,I ignore this error,into check:data.  
result.Block.Timestamp is 1602934283637 ==> 2020-10-17 19:31:23,but rosetta-cli tell me :
Command Failed: unable to fetch block 1: timestamp is before 01/01/2000: 0: /block: /block not attempting retry: unable to sync to 117326642: unable to sync to 117326642
