### ISSUE TITLE
check:construction => unable to construct payloads: unable to create transaction???

### ISSUE THREAD

**Issue by Li-LaoShi** [coinbase/rosetta-cli#360]
hello ,my friend.I meet a question :
`Command Failed: request failed: /construction/payloads invalid status code: 404 body: : unable to construct payloads: unable to create transaction`
but my /construction/payloads and /metadata is ok,I don't know  where is the problem?
if you see it ,please tell me answer. thank you very much!!!

**Comment by GeekArthur** [comment]
That means your `/construction/payloads` response doesn't return anything, probably it's not implemented properly, you have to follow the instruction https://www.rosetta-api.org/docs/ConstructionApi.html#response-5 to ensure the response is returned and correct

**Comment by Li-LaoShi** [comment]
/construction/metadata ：Does it need to be async(await) processing?
 What is the connection between  /construction/metadata and /construction/payloads ？？
I think the options information in xx.ros needs /metadata to be passed to /payloads . Is that so?
