### ISSUE TITLE
"Process stalled" error message

### ISSUE THREAD

**Issue by rllola** [coinbase/rosetta-cli#369]
I am still trying to run `check:construction` and now that I have increased the tip_delay so it can start, I have this error message.

```
2022/10/12 14:45:11 Syncing 12575433-12575434
processing stalled
[MEMORY] Heap: 1103.368118MB Stack: 0.656250MB System: 1160.534706MB GCs: 6
2022/10/12 14:45:12 check:construction status server shutting down
```

I have no clue why it is shutting down on its own like this. Any ideas?

**Comment by GeekArthur** [comment]
[Here](https://github.com/coinbase/rosetta-sdk-go/blob/18b582a021493f73627d8f6681d19eeccb4b711a/constructor/coordinator/errors.go#L44-L46) is the definition of `processing stalled`, can you check if the workflows (e.g. CreateAccount) in `*.ros` file is defined properly?

And [this](https://github.com/coinbase/rosetta-sdk-go/blob/18b582a021493f73627d8f6681d19eeccb4b711a/constructor/coordinator/coordinator.go#L215) is where we return `processing stalled`, if the workflows are not defined properly finally it will return that error message

**Comment by rllola** [comment]
Here the .ros file
```
create_account(1){
  create{
    network = {"network":"cosmoshub-4 ", "blockchain":"Cosmos"};
    key = generate_key({"curve_type": "secp256k1"});
    account = derive({
      "network_identifier": {{network}},
      "public_key": {{key.public_key}}
    });

    // If the account is not saved, the key will be lost!
    save_account({
      "account_identifier": {{account.account_identifier}},
      "keypair": {{key}}
    });
  }
}
```

I didn't write this so I assume it was working before...

**Comment by GeekArthur** [comment]
This is an example from [ethereum.ros](https://github.com/coinbase/rosetta-ethereum/blob/master/rosetta-cli-conf/testnet/ethereum.ros), and [here](https://www.rosetta-api.org/docs/rosetta_dsl_file.html) is the instruction of how to write `*.ros`, you may use them as reference

You may wait for your chain to sync to tip then give a try, if this issue still exists you may use the debugger to deep dive what actually happen in the `*.ros`

**Comment by rllola** [comment]
I found the issue. It is because it is **required** to have at least 2 workflows : request and create.

It is written in the documentation
![Screenshot from 2022-10-14 09-31-50](https://user-images.githubusercontent.com/1772945/195793618-b13d5517-4247-497e-aaa4-8924c3e02bba.png)

I don't know if there is a way to improve the error message or to quickly check the .ros file to be sure it include those 2.

**Comment by GeekArthur** [comment]
Thanks for bringing this up, I am gonna improve the error message for this
