### ISSUE TITLE
Installing on Mac OS X with latest go broken

### ISSUE THREAD

**Issue by almindor** [coinbase/rosetta-cli#45]
**Describe the bug**
Installing on Mac OS X with latest go 1.14.4 results in this error:
```
# github.com/dgraph-io/badger/pb
../../go/src/github.com/gdraph-io/badger/pb/pb.pb.go:23:11: undefined:
proto.ProtoPackageIsVersion3
```

**To Reproduce**
`go get github.com/coinbase/rosetta-cli`

**Expected behavior**
Rosetta-cli to install

**Additional context**
Protobufs need regen for go v1.14.x

**Comment by patrick-ogrady** [comment]
This is now resolved with the ability to install pre-compiled binaries: https://github.com/coinbase/rosetta-cli/issues/116#issuecomment-685793552
