### ISSUE TITLE
Allow passing a configuration file to the validator

### ISSUE THREAD

**Issue by LindaOrtega** [coinbase/rosetta-cli#47]
**Is your feature request related to a problem? Please describe.**
The `check` command doesn't automatically validate all sub-networks in a sharded blockchain (it validates the first sub-network it sees). I'd want to be able to manually run the validator against different sub-networks.

**Describe the solution you'd like**
The ability to pass a configuration file to the validator's `check` command. For example, the validator currently supports creating a configuration file using the `create:configuration` command. It would be useful to edit this configuration to target a specific sub-network and pass this to the `check` command.

**Describe alternatives you've considered**
I've been able to edit the rosetta `/network/list` endpoint logic to return a specific sub-network during testing. But this is not ideal when testing multiple sub-networks simultaneously.

**Comment by patrick-ogrady** [comment]
Our plan is to have 2 modes for validating multiple networks: validate all sub-networks (default) and validate a particular sub-network (using a command line arg).

I hadn't thought about `rosetta-cli` initialization using a config file but it makes sense! We will think about the best way to do this.
