### ISSUE TITLE
[Check] Run the validator on _all_ sub-networks

### ISSUE THREAD

**Issue by LindaOrtega** [coinbase/rosetta-cli#48]
**Is your feature request related to a problem? Please describe.**
Our blockchain has 10 sub-networks (called "chains" in our nomenclature), but `rosetta-cli check` only validates the first sub-network it sees.

**Describe the solution you'd like**
Validate all sub-networks, if multiple exist. It seems that this is known issue:
https://github.com/coinbase/rosetta-cli/blob/master/cmd/check.go#L499

**Describe alternatives you've considered**
This is related to another issued I opened: https://github.com/coinbase/rosetta-cli/issues/47
But, in general, the work around has been to manually change the node's rosetta implementation to return the specific sub-network I want to test.

**Comment by patrick-ogrady** [comment]
This is something we are actively working on now @LindaOrtega (apologize for the delay!). We expect to have support for checking multiple sub-networks in the coming days.
