### ISSUE TITLE
ignore --bootstrap-balances flag when resuming check from a data dir

### ISSUE THREAD

**Issue by yutongp** [coinbase/rosetta-cli#50]
**Is your feature request related to a problem? Please describe.**
currently with an existing data dir, and `--bootstrap-balances` flag, the cli return error:
`2020/07/08 22:38:36 cannot bootstrap accounts, already started syncing: unable to bootstrap balances`

**Describe the solution you'd like**
Would be nice, if rosetta-cli ignore `--bootstrap-balances` flag when resuming from an existing check, so user can simply use one command to start a check and resume from a check.

**Comment by patrick-ogrady** [comment]
Thanks for posting this issue @yutongp! This will make it into https://github.com/coinbase/rosetta-cli/milestone/1!
