### ISSUE TITLE
Add a new check flag to cover all recorded addresses

### ISSUE THREAD

**Issue by CipherWang** [coinbase/rosetta-cli#54]
**Is your feature request related to a problem? Please describe.**
When checking the balance reconciliation, the `rosetta-cli` has only two possible working patterns. One pattern is checking the `active addresses` related to the operations in new blocks, the other one is checking the `inactive addresses` randomly selected from previous records. But even after a very long time, the `rosetta-cli` only randomly chooses a limited subset of the addresses, it cannot cover all possible addresses.

**Describe the solution you'd like**
Maybe we could add a new `--all-address-check` flag to the check command to check them all. It will start the full checking process after the `rosetta-cli` check runs to the tip.

**Comment by patrick-ogrady** [comment]
Thanks for posting about this @CipherWang!

@metajack posted about a similar issue in https://github.com/coinbase/rosetta-sdk-go/issues/65 and I merged a ton of improvements to the reconciler that greatly improve the `inactive` reconciliation loop in https://github.com/coinbase/rosetta-sdk-go/pull/66.

I also added a new flag in #56 to make it possible to check all `inactive` addresses at each block! To perform this "all addresses check" you would run `rosetta-cli check --inactive-reconciliation-frequency=1` (adding `--lookup-balance-by-block=false` if your implementation doesn't support historical balance lookup). If you enable this flag, I'd also recommend setting `--inactive-reconciliation-concurrency=64` (as the default of 4 will not be sufficient if there are many accounts).
