### ISSUE TITLE
Unreviewed commit on master!

### ISSUE THREAD

**Issue by heimdall-asguard** [coinbase/rosetta-cli#72]
Unreviewed commit(s) [COMPARE](https://github.com/coinbase/rosetta-cli/compare/33358ed9bb29acf387f19190b7a3d90e1bda612c...00983ddd1d6091d560d66658ff52c32cd6c9b99c) was merged to master by patrick-ogrady.

Comment with appropriate number of :+1: to approve.

**Comment by heimdall-asguard** [comment]
Minimum Reviews      | 0/1
------------ | -------------






[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/rosetta-cli&ref=00983ddd1d6091d560d66658ff52c32cd6c9b99c)

**Comment by slowboat0** [comment]
👍

**Comment by heimdall-asguard** [comment]
Minimum Reviews      | 2/1
------------ | -------------
juliankoh | 1
slowboat0 | 1



Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/rosetta-cli&ref=00983ddd1d6091d560d66658ff52c32cd6c9b99c)
